kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gke-filestore-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard-rwx # creates filestore instance
  resources:
    requests:
      storage: 1Ti