apiVersion: batch/v1
kind: Job
metadata:
  name: k8sapp-job
spec:
  completions: 1
  template:
    spec:
      containers:
      - name: k8sapp-job
        image: php:7.4-cli
        command: ["php", "-v"]
      restartPolicy: Never

