apiVersion: v1
kind: Service
metadata:
  name: k8sapp-node-port-service
spec:
  selector:
    app: k8sapp-deployment
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31610     