apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment-server
  labels:
    app: wordpress-app
spec:
  selector:
    matchLabels:
      app: wordpress-app
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress-app
          image: 'wordpress:latest'
          ports:
            - containerPort: 8000
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secrets
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wp-config
                  key: WORDPRESS_DB_NAME
