apiVersion: v1
kind: Pod
metadata:
  name: wid-demo-with-sa
  namespace: kns
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: wid-demo-with-sa
    command: ["sleep","infinity"]
  serviceAccountName: ksa
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"


# steps 
# 1- Create GCP IAM Service Account : gcloud iam service-accounts create GSA_NAME --project=GSA_PROJECT_ID
# 2- Add IAM Roles to GCP IAM Service Account  gcloud projects add-iam-policy-binding PROJECT_ID --member "serviceAccount:GSA_NAME@GSA_PROJECT_ID.iam.gserviceaccount.com" --role "ROLE_NAME"  
# 3- Create Service Account : kubectl create serviceaccount <KSA_NAME>
# 4- Associate GCP IAM Service Account with Kubernetes Service Account : gcloud iam service-accounts add-iam-policy-binding GSA_NAME@GSA_PROJECT_ID.iam.gserviceaccount.com --role roles/iam.workloadIdentityUser --member "serviceAccount:PROJECT_ID.svc.id.goog[NAMESPACE/KSA_NAME]"
# 5- Annotate Kubernetes Service Account with GCP IAM SA email Address : kubectl annotate serviceaccount KSA_NAME --namespace NAMESPACE iam.gke.io/gcp-service-account=GSA_NAME@GSA_PROJECT_ID.iam.gserviceaccount.com