apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
        tier: backend
    spec:
      # volumes:
      #   - name: vol-test
      #     persistentVolumeClaim:
      #       claimName: my-pvc
          # hostPath:
          #   path: /data/logs
            
      containers:
        - name: laravel-app
          image: "omar2023/lara101:lara101-v1"
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh" , "-c" , "service nginx start"]
          # acts as .env file      
          env:              
           - name: DB_HOST
             value: "mysql-externalname-service"
           - name: DB_PORT
             value: "3306"
           - name: DB_DATABASE
             value: "lara101_db"    
           - name: DB_USERNAME
             value: root
           - name: DB_PASSWORD
             valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password   
          # volumeMounts:
          #   - mountPath: usr/share/nginx/html
          #     name: vol-test
              

# ClusterIp Service
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service # will be used in pass proxy nginx front end app 
  labels:
    app: backend-laravel-app
    tier: backend   
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: backend-deployment
