apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-nginx-deployment
  labels:
    app: app3-nginx 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3-nginx
  template:
    metadata:
      labels:
        app: app3-nginx
    spec:
      containers:
        - name: app3-nginx
          image: stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80
          readinessProbe:        # CUSTOM HEALTH CHECK
              httpGet:
                scheme: HTTP
                path: app3/index.html
                port: 80
              initialDelaySeconds: 10
              periodSeconds: 15
              timeoutSeconds: 5     
---
apiVersion: v1
kind: Service
metadata:
  name: app3-nginx-nodeport-service
  labels:
    app: app3-nginx
  annotations:
    cloud.google.com/backend-config: '{"default": "my-backendconfig"}' # default for the current node port
spec:
  type: NodePort
  selector:
    app: app3-nginx
  ports:
    - port: 80
      targetPort: 80