apiVersion: v1
kind: Service
metadata:
  name: frontend-lb-service
  namespace: app
  labels:
    app: frontend-nginxapp
    tier: frontend  
spec:
  type: LoadBalancer
  selector:
    app: frontend-deployment
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
         