apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-myapp1
 namespace: app
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: backend-app-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50